import { StyleSheet } from "react-native";

export const challengesStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
    padding: 14,
    paddingBottom: 0,
  },
  backgroundImage: {
    opacity: 1,
    resizeMode: "cover",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: "#F3F4F6",
  },
  statItem: {
    alignItems: "center",
  },
  statNumber: {
    fontSize: 28,
    fontWeight: "700",
    color: "#4F46E5",
    letterSpacing: 0.5,
  },
  statLabel: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 6,
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  locationBanner: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EEF2FF",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderLeftWidth: 5,
    borderLeftColor: "#4F46E5",
    shadowColor: "#4F46E5",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  locationBannerText: {
    fontSize: 16,
    color: "#4F46E5",
    marginLeft: 12,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  listContainer: {
    paddingBottom: 24,
  },
  questCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: "#F3F4F6",
  },
  questHeader: {
    marginBottom: 16,
  },
  questTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  categoryIcon: {
    marginRight: 12,
  },
  questTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#1F2937",
    flex: 1,
    letterSpacing: 0.2,
  },
  difficultyBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  difficultyText: {
    fontSize: 11,
    fontWeight: "700",
    color: "white",
    marginLeft: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  questDescription: {
    fontSize: 15,
    color: "#6B7280",
    lineHeight: 22,
    marginBottom: 16,
    fontWeight: "400",
  },
  locationRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  locationText: {
    fontSize: 12,
    color: "#666",
    marginLeft: 5,
    fontStyle: "italic",
  },
  questFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  xpContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  xpText: {
    fontSize: 15,
    fontWeight: "700",
    color: "#F59E0B",
    marginLeft: 6,
    letterSpacing: 0.3,
  },
  questActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  questButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 24,
    marginRight: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  startButton: {
    backgroundColor: "#4F46E5",
  },
  completedButton: {
    backgroundColor: "#10B981",
  },
  disabledButton: {
    backgroundColor: "#9CA3AF",
  },
  buttonText: {
    color: "white",
    fontWeight: "600",
    fontSize: 13,
    marginLeft: 6,
    letterSpacing: 0.2,
  },
  deleteButton: {
    padding: 10,
  },
  requirementsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  requirementsText: {
    fontSize: 12,
    color: "#666",
    marginLeft: 5,
    fontStyle: "italic",
  },
  availabilityRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  availabilityText: {
    fontSize: 12,
    color: "#666",
    marginLeft: 5,
    fontStyle: "italic",
  },
  analyticsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "rgba(0, 122, 255, 0.05)",
    borderRadius: 8,
    padding: 10,
    marginBottom: 12,
  },
  analyticsItem: {
    alignItems: "center",
  },
  analyticsLabel: {
    fontSize: 10,
    color: "#666",
    textTransform: "uppercase",
  },
  analyticsValue: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    marginTop: 2,
  },
  bonusText: {
    fontSize: 10,
    color: "#FF9500",
    marginLeft: 8,
    fontWeight: "bold",
  },
  eligibilityWarning: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 149, 0, 0.1)",
    borderRadius: 8,
    padding: 8,
    marginTop: 8,
  },
  eligibilityText: {
    fontSize: 12,
    color: "#FF9500",
    marginLeft: 5,
    fontStyle: "italic",
  },
  mapToggleButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: "#F1F5F9",
  },
});
