import { StyleSheet } from "react-native";

export const leaderboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
    padding: 0,
  },
  backgroundImage: {
    opacity: 0.05,
    resizeMode: "cover",
  },
  header: {
    backgroundColor: "#FFFFFF",
    paddingTop: 50,
    paddingBottom: 20,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    marginBottom: 20,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginHorizontal: 12,
    textAlign: "center",
  },
  headerSubtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    fontWeight: "500",
  },
  headerControls: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 20,
    marginBottom: 20,
    gap: 12,
  },
  periodSelector: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 16,
    padding: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  refreshButton: {
    width: 44,
    height: 44,
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  periodButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  activePeriodButton: {
    backgroundColor: "#137CD8",
    shadowColor: "#137CD8",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  periodButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "#8E8E93",
    textTransform: "capitalize",
    letterSpacing: 0.3,
  },
  activePeriodButtonText: {
    color: "white",
    fontWeight: "700",
  },
  podiumContainer: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 24,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.08,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: "#F3F4F6",
  },
  podiumTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 15,
    color: "#333",
  },
  podium: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
  },
  podiumPlace: {
    alignItems: "center",
    flex: 1,
  },
  podiumBadge: {
    fontSize: 32,
    marginBottom: 8,
  },
  podiumName: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginBottom: 4,
  },
  podiumXP: {
    fontSize: 10,
    color: "#666",
    marginBottom: 8,
  },
  podiumRank: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  podiumRankText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "white",
  },
  statsBanner: {
    backgroundColor: "rgba(19, 124, 216, 0.1)",
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: "#137CD8",
  },
  globalStat: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  globalStatText: {
    fontSize: 14,
    color: "#137CD8",
    marginLeft: 8,
    fontWeight: "500",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
  },
  listContainer: {
    paddingBottom: 20,
  },
  leaderboardItem: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 16,
    width: "93%",
    alignSelf: "center",
    marginBottom: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: "#F0F0F0",
  },
  currentUserItem: {
    backgroundColor: "#F0F8FF",
    borderColor: "#137CD8",
    borderWidth: 2,
    shadowColor: "#137CD8",
    shadowOpacity: 0.15,
    transform: [{ scale: 1.02 }],
  },
  rankContainer: {
    alignItems: "center",
    marginRight: 16,
    minWidth: 50,
  },
  rankText: {
    fontSize: 14,
    fontWeight: "bold",
    marginTop: 4,
    textAlign: "center",
  },
  currentUserBadge: {
    backgroundColor: "#137CD8",
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
    marginTop: 4,
  },
  currentUserBadgeText: {
    fontSize: 8,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
  },
  explorerInfo: {
    flex: 1,
  },
  explorerHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  profilePhotoContainer: {
    marginRight: 12,
  },
  profilePhoto: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#137CD8",
  },
  profilePhotoPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#137CD8",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#137CD8",
  },
  profilePhotoText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "white",
  },
  explorerBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#FFF8DC",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    borderWidth: 2,
    borderColor: "#FFD700",
  },
  nameAndTitle: {
    flex: 1,
    marginRight: 8,
  },
  explorerName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginBottom: 2,
  },
  explorerTitle: {
    fontSize: 12,
    color: "#666",
    fontStyle: "italic",
  },
  levelBadge: {
    backgroundColor: "#137CD8",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
  },
  levelText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "white",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#F0F0F0",
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
    paddingVertical: 4,
  },
  statValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#1a1a1a",
    marginLeft: 4,
    marginRight: 2,
  },
  statLabel: {
    fontSize: 10,
    color: "#666",
    fontWeight: "500",
  },
  viewProfileIcon: {
    marginLeft: 8,
    padding: 8,
    borderRadius: 20,
    backgroundColor: "#F0F8FF",
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 60,
    paddingHorizontal: 40,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#8E8E93",
    textAlign: "center",
    marginTop: 16,
    marginBottom: 8,
  },
  emptyStateSubtitle: {
    fontSize: 14,
    color: "#C7C7CC",
    textAlign: "center",
    lineHeight: 20,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 60,
  },
  loadingText: {
    fontSize: 16,
    color: "#666",
    marginTop: 16,
    fontWeight: "500",
  },
  teamHeader: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 8,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: "#137CD8",
  },
  teamName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#1a1a1a",
    marginLeft: 8,
    flex: 1,
  },
  teamMemberCount: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
  },
  avatarContainer: {
    marginRight: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 2,
    borderColor: "#E5E5EA",
  },
  defaultAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#E5E5EA",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarInitials: {
    fontSize: 16,
    fontWeight: "600",
    color: "#666",
  },
  infoContainer: {
    flex: 1,
    marginRight: 8,
  },
  levelContainer: {
    backgroundColor: "#F0F0F0",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 8,
  },
  challengeButtonSmall: {
    backgroundColor: "rgba(214, 26, 102, 0.1)",
    padding: 8,
    borderRadius: 16,
    marginRight: 8,
  },
  challengeButton: {
    backgroundColor: "rgba(214, 26, 102, 0.1)",
    padding: 8,
    borderRadius: 16,
    marginLeft: 8,
  },
  statText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#333",
    marginLeft: 4,
  },
  statDivider: {
    width: 1,
    height: 16,
    backgroundColor: "#E5E5EA",
    marginHorizontal: 8,
  },
});
