import { StyleSheet } from "react-native";

export const leaderboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
    padding: 20,
  },
  periodSelector: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 25,
    padding: 4,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  periodButton: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    alignItems: "center",
  },
  activePeriodButton: {
    backgroundColor: "#007AFF",
  },
  periodButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#666",
    textTransform: "capitalize",
  },
  activePeriodButtonText: {
    color: "white",
    fontWeight: "bold",
  },
  podiumContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 15,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  podiumTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 15,
    color: "#333",
  },
  podium: {
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "flex-end",
  },
  podiumPlace: {
    alignItems: "center",
    flex: 1,
  },
  podiumBadge: {
    fontSize: 32,
    marginBottom: 8,
  },
  podiumName: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#333",
    textAlign: "center",
    marginBottom: 4,
  },
  podiumXP: {
    fontSize: 10,
    color: "#666",
    marginBottom: 8,
  },
  podiumRank: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  podiumRankText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "white",
  },
  statsBanner: {
    backgroundColor: "rgba(0, 122, 255, 0.1)",
    borderRadius: 12,
    padding: 15,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: "#007AFF",
  },
  globalStat: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  globalStatText: {
    fontSize: 14,
    color: "#007AFF",
    marginLeft: 8,
    fontWeight: "500",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 15,
  },
  listContainer: {
    paddingBottom: 20,
  },
  leaderboardItem: {
    flexDirection: "row",
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    borderRadius: 15,
    padding: 15,
    marginBottom: 10,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  currentUserItem: {
    borderWidth: 2,
    borderColor: "#007AFF",
    backgroundColor: "rgba(0, 122, 255, 0.05)",
  },
  rankContainer: {
    alignItems: "center",
    marginRight: 15,
    minWidth: 50,
  },
  rankText: {
    fontSize: 12,
    fontWeight: "bold",
    marginTop: 4,
  },
  explorerInfo: {
    flex: 1,
  },
  explorerHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  explorerBadge: {
    fontSize: 24,
    marginRight: 12,
  },
  nameAndTitle: {
    flex: 1,
  },
  explorerName: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#333",
  },
  explorerTitle: {
    fontSize: 12,
    color: "#666",
    fontStyle: "italic",
  },
  levelBadge: {
    backgroundColor: "#007AFF",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  levelText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "white",
  },
  statsContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
  },
  statItem: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  statValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
    marginLeft: 4,
    marginRight: 2,
  },
  statLabel: {
    fontSize: 10,
    color: "#666",
  },
});
