export const settingsStyles = {
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  backgroundImage: {
    opacity: 0.08,
    resizeMode: "cover" as const,
  },
  scrollContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 60,
    paddingTop: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    backgroundColor: "transparent",
    paddingHorizontal: 32,
  },
  loadingText: {
    marginTop: 24,
    color: "#4B5563",
    fontSize: 20,
    fontWeight: "600" as const,
    textAlign: "center" as const,
  },
  header: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    paddingHorizontal: 24,
    paddingVertical: 16,
    marginTop: 20,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    backdropFilter: "blur(20px)",
    borderBottomWidth: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  backButton: {
    padding: 10,
    borderRadius: 12,
    backgroundColor: "rgba(248, 249, 250, 0.8)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    width: 44,
    height: 44,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "700" as const,
    color: "#111827",
    letterSpacing: 0.3,
  },
  placeholder: {
    width: 44,
  },
  content: {
    flex: 1,
    paddingTop: 0,
  },
  section: {
    marginTop: 32,
    paddingHorizontal: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "700" as const,
    color: "#374151",
    marginBottom: 12,
    marginLeft: 8,
    textTransform: "uppercase" as const,
    letterSpacing: 1.2,
    opacity: 0.8,
  },
  // Profile Image Styles
  profileImageContainer: {
    alignItems: "center" as const,
    paddingVertical: 32,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    backdropFilter: "blur(20px)",
    borderRadius: 24,
    marginHorizontal: 16,
    marginTop: 16,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 16,
    elevation: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#007AFF",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    marginBottom: 16,
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 12,
    borderWidth: 4,
    borderColor: "#FFFFFF",
  },
  avatarText: {
    fontSize: 28,
    fontWeight: "700" as const,
    color: "#FFFFFF",
    letterSpacing: 1,
  },
  changeImageButton: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    backgroundColor: "#007AFF",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },
  changeImageText: {
    color: "#FFFFFF",
    fontWeight: "600" as const,
    marginLeft: 6,
    fontSize: 14,
  },
  avatarContainer: {
    position: "relative" as const,
    marginBottom: 16,
  },
  avatarImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 12,
    borderWidth: 4,
    borderColor: "#FFFFFF",
  },
  cameraIconOverlay: {
    position: "absolute" as const,
    bottom: 4,
    right: 4,
    backgroundColor: "#007AFF",
    borderRadius: 14,
    width: 28,
    height: 28,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    borderWidth: 2,
    borderColor: "#FFFFFF",
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
  },
  // Setting Item Styles
  settingItem: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    backdropFilter: "blur(20px)",
    borderRadius: 16,
    padding: 18,
    marginHorizontal: 16,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    minHeight: 64,
  },
  settingLeft: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    flex: 1,
  },
  settingInfo: {
    marginLeft: 14,
    flex: 1,
  },
  settingLabel: {
    fontSize: 16,
    fontWeight: "600" as const,
    color: "#1F2937",
    letterSpacing: 0.2,
  },
  settingValue: {
    fontSize: 13,
    color: "#6B7280",
    marginTop: 2,
    lineHeight: 16,
    fontWeight: "500" as const,
  },
  signOutButton: {
    backgroundColor: "rgba(254, 242, 242, 0.95)",
    marginTop: 24,
    marginBottom: 40,
    borderColor: "rgba(248, 113, 113, 0.3)",
    borderWidth: 1,
  },
  signOutText: {
    color: "#DC2626",
    fontWeight: "600" as const,
    fontSize: 16,
  },
  // Setting Slider Styles
  settingSlider: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    backdropFilter: "blur(20px)",
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 6,
    overflow: "hidden" as const,
    position: "relative" as const,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    minHeight: 72,
  },
  settingSliderContent: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    padding: 20,
    paddingLeft: 76,
    zIndex: 2,
    minHeight: 72,
  },
  slideHint: {
    alignItems: "flex-end" as const,
    opacity: 0.7,
  },
  slideHintText: {
    fontSize: 11,
    color: "#007AFF",
    fontWeight: "600" as const,
    marginBottom: 2,
    letterSpacing: 0.6,
    textTransform: "uppercase" as const,
  },
  slideBlob: {
    position: "absolute" as const,
    left: 8,
    top: 8,
    bottom: 8,
    width: 56,
    backgroundColor: "#007AFF",
    borderRadius: 12,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    zIndex: 1,
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  // New Card Group Style
  cardGroup: {
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    backdropFilter: "blur(20px)",
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    overflow: "hidden" as const,
  },
  cardGroupTitle: {
    fontSize: 16,
    fontWeight: "700" as const,
    color: "#374151",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 12,
    textTransform: "uppercase" as const,
    letterSpacing: 1,
    opacity: 0.8,
  },
};
